### ISSUE TITLE
Simple SELECT queries (Single WHERE clause and no JOINS).

### ISSUE THREAD

**Issue by grzesiekb** [joaoh82/rust_sqlite#3]
## Expect 
Simple SELECT queries (Single WHERE clause and no JOINS).

## 
Recognition how to do it 
1. recognising how it is done in sqllite.

**Comment by joaoh82** [comment]
Sounds good. I am actually also working on this one. So if you could share your design before hand, that would be great.

**Comment by grzesiekb** [comment]
I think it might be a good idea. Then we can set up a topic to discuss how to do it. In SQLLite interpreted "select" is broken down into many smaller functions so I think this could be a topic for more than one person.

**Comment by joaoh82** [comment]
Btw, I created a discord server for the project so we can start have a more active conversation and build a community. Here is the link: https://discord.gg/zHXUG66X .
